[package]
name = "riff"
version = "0.1.0"
authors = ["Francesco Bertolaccini <bertolaccinifrancesco@gmail.com>"]
description = "This crate provides utilities for reading and writing RIFF formatted files"
repository = "https://github.com/frabert/riff"
readme = "README.md"
license = "MIT"

[dependencies]
byteorder = "1"
